global:
  resolve_timeout: 1m
  smtp_from: 'your-email@gmail.com'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-gmail-app-password'
  smtp_require_tls: true

route:
  receiver: 'email-notifications'
  repeat_interval: 5m
  routes:
    - match:
        severity: critical
      receiver: email-notifications

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'recipient-email@example.com'
    send_resolved: true
    html: '<html><body><h1>Alert: {{ .Status }}</h1><p>{{ .CommonAnnotations.description }}</p></body></html>'
