global:
  resolve_timeout: 1m
  smtp_from: 'your-email@gmail.com'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-gmail-app-password'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  receiver: 'email-notifications'
  repeat_interval: 5m

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'recipient-email@example.com'
    send_resolved: true
