version: '3.7'
services:
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "5005:8080"
    networks:
      - project_project_network
      
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--web.enable-lifecycle'
    networks:
      - project_project_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana
      - ./grafana/data:/var/lib/grafana
      - ./grafana/logs:/var/log/grafana/logs
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/sessions:/var/lib/grafana/sessions
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
    networks:
      - project_project_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager_data:/var/lib/alertmanager
    ports:
      - "9093:9093"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/var/lib/alertmanager'
      - '--web.external-url=http://localhost:9093'
    networks:
      - project_project_network

  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/blackbox.yml
    command:
      - '--config.file=/etc/blackbox_exporter/blackbox.yml'
    networks:
      - project_project_network

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - project_project_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - project_project_network

networks:
  project_project_network:
    driver: bridge
    internal: false
volumes:
  grafana-storage:
    external: true

